### ISSUE TITLE
Make Map Tests

### ISSUE THREAD

**Issue by dakotaraymccoy** [enartey/WebAppsLabs#16]
1. Creates a makeMap function that takes no arguments and creates a new "empty map"
2. makeMap returns object with the following functions:
   `has`: Calling`theMap.has(key)` should return a boolean saying if your map has a key that equals the passed argument.
   
   `lookup`: Calling `theMap.lookup(key)` should return the value stored in that key. It should throw an error if the key does not exist.
   
   `add`: Calling `theMap.add(key, value)` should add the key-value pair to the map and return `theMap` (so that calls can be chained). It should throw an error if the key already exists.
   
   `update`: Calling `theMap.update(key, value)` should update the value associated with the key. It should return `theMap` to allow chaining. If the key does not already exist in the map, it should throw an error.
   
   `remove`: Calling `theMap.remove(key)` should remove the pair stored in that key. It should throw an error if the key does not exist in the map.
- Your methods must make a distinction between "having a key with corresponding value `undefined/null`" and "not having the key at all". Using "`hasOwnProperty" at appropriate places should do this for you. Make sure your tests test for this.
- The messages for the errors you throw should include in their text enough information to know that it is regarding the "map" structure, which method had problems, and what the key was. This will not be checked in our tests however, we will only test that an error happens.
- The test file provides you with a function `randomString` that you can use to generate random strings for your tests. It takes as input the length of the resulting string, defaulting to 5.

**Comment by dakotaraymccoy** [comment]
@skiadas

When writing our first describe for the makeMap test, the index file doesn't show anything when run in the browser. Our code for the describe is this:

decribe('Your code for Map Structure', function(){
   it('defines a variable makeMap', function(){
      expect(function() {makeMap;}).to.not.throw(Error);
   });
   it('actually defines a function', function(){
      expect(makeMap.to.be.a('function');
   });
});

**Comment by skiadas** [comment]
Ok if your code is exactly like that, then you should see an error in the web console. You are missing a second parenthesis at `'function')`, to close the `expect`.

Tip: Use three backslashes to start and end code blocks in the comments, it will show them better.

**Comment by skiadas** [comment]
Hm, sorry, the parenthesis should be after `makeMap`, so:

```
expect(makeMap).to.be.a('function');
```

**Comment by skiadas** [comment]
@dakotaraymccoy I'm curious, did it notify you for all 3 posts, or just this last one?

**Comment by enartey** [comment]
it notified all of us

**Comment by skiadas** [comment]
Nice. I think it notified you because it is your repository, and dakota because he started / participated in the issue.

**Comment by enartey** [comment]
cool, so something like this? 
///
decribe('Your code for Map Structure', function(){
   it('defines a variable makeMap', function(){
      expect(function() { makeMap; }).to.not.throw(Error);
   });
   it('actually defines a function', function(){
      expect(makeMap).to.be.a('function');
   });
});
///

**Comment by enartey** [comment]
oh sorry 

\\\
decribe('Your code for Map Structure', function(){
   it('defines a variable makeMap', function(){
      expect(function() { makeMap; }).to.not.throw(Error);
   });
   it('actually defines a function', function(){
      expect(makeMap).to.be.a('function');
   });
});
\\\

**Comment by enartey** [comment]
\\\

decribe('Your code for Map Structure', function(){
   it('defines a variable makeMap', function(){
      expect(function() { makeMap; }).to.not.throw(Error);
   });
   it('actually defines a function', function(){
      expect(makeMap).to.be.a('function');
   });
});

\\\
sorry for the emails. Just testing this

**Comment by skiadas** [comment]
Backticks, not backslashes ;). "`". If you look in the README.md you'll see many examples.

You can also edit your comments.

**Comment by enartey** [comment]
```
decribe('Your code for Map Structure', function(){
   it('defines a variable makeMap', function(){
      expect(function() { makeMap; }).to.not.throw(Error);
   });
   it('actually defines a function', function(){
      expect(makeMap).to.be.a('function');
   });
});
```

**Comment by skiadas** [comment]
If you put the word "javascript" right after the opening backticks, "```javascript", it should in fact color-code the block as javascript. (I hope at least. let me see).

``` javascript
decribe('Your code for Map Structure', function(){
   it('defines a variable makeMap', function(){
      expect(function() { makeMap; }).to.not.throw(Error);
   });
   it('actually defines a function', function(){
      expect(makeMap).to.be.a('function');
   });
});
```

**Comment by enartey** [comment]
yes it shows color. thanks
