### ISSUE TITLE
Typo in lab assignment?

### ISSUE THREAD

**Issue by dakotaraymccoy** [enartey/WebAppsLabs#17]
@skiadas

"tags: This should be an array, starting as empty, meant to contain a list of the string "tags" attached to this task. This variable should be not configurable, not writeable and not enumerable. We will create specific methods to interface with it instead."

This tells us that the property "tags" should be not configurable, not writeable and not enumerable. However,  it also says ' "id" and "tags" will require the use of Object.defineProperty.'.

If everything defaults to false, why would we need defineProperty for this? Is there just a simple typo or are we missing something?

**Comment by skiadas** [comment]
They only default to false if you use `Object.defineProperty` to define that property.

You can also define a property by simply writing: `a.foo = 5`. When a property is created that way, it is both configurable and enumerable, and also writable.
