### ISSUE TITLE
addNewTask

### ISSUE THREAD

**Issue by enartey** [enartey/WebAppsLabs#20]
This function triggers when the Add button is pressed. Start by putting a console.log in it and what it trigger when you press the Add button on the web page. It creates a new default string, pushes it into the tasks array, then creates and adds the appropriate HTML to the page.

**Comment by enartey** [comment]
when you say push the string and add "new task" at the end is this what you mean? @skiadas

``` Javascript
   function addNewTask(ev) {
    var newTask = ev+"New Task";
    tasks.push(newTask);
    var taskHTML = newTaskHTML(ev);
    taskHTML.insertAfter(el);
    return true;
   };
```

**Comment by skiadas** [comment]
Overall yes, but some details worry me. "ev" usually is an event object, so `ev+"New Task"` does not make much sense, and similarly newTaskHTML should be passed a string, not an event object. But otherwise you got the right idea.

**Comment by enartey** [comment]
cool,thanks @skiadas
