### ISSUE TITLE
eslintLab4

### ISSUE THREAD

**Issue by enartey** [enartey/WebAppsLabs#29]
running eslint on the file to get rid of all errors before proceeding

**Comment by enartey** [comment]
@skiadas is there w way to ignore the "'$' is not defined error" in eslint?

it is also complaining about 

``` Javascript

var el = $(element);

   // "tasks" is an array of strings for the tasks to be shown.
   var tasks = [];

```

being on separate lines...shd I change this or leave it alone since you gave us this code?

**Comment by skiadas** [comment]
Look into how to add a eslint global directive into your file, you can tell it $ should be defined
