### ISSUE TITLE
Given code still not working

### ISSUE THREAD

**Issue by dakotaraymccoy** [enartey/WebAppsLabs#5]
The following code is not working. We are on the step to insert the it statement and expect statement, which we have copy/pasted according to instruction. It says it should fail the test, but it is passing. The code we have is this:

try {
   var chai = require('./chai.js');
   var expect = chai.expect;
   var methods = require('./yourCode.js');
   var binarySearch = methods.binarySearch;
   var countTags = methods.countTags;
   var extractHashTags = methods.extractHashTags;
} catch (e) {}

// Do not change anything above this line

describe('Your code for stacks', function() {
   it('defines a variable makeStack', function() {
    expect(function() { makeStack; }).to.not.throw(Error);
   });
   // Add more "it" sections below
});

@skiadas

**Comment by skiadas** [comment]
@dakotaraymccoy Ah, typo in my suggested text. You need to be _calling_ the function makeStack, so need to have:

```
expect(function() { makeStack(); }).to.not.throw(Error);
```

**Comment by skiadas** [comment]
@dakotaraymccoy oops i responded too hastily. The line was correct as it was:

```
expect(function() { makeStack; }).to.not.throw(Error);
```

This line should produce an error if you have NOT declared something called makeStack in your code. On the other hand if you have it declared then you will not see a failure.

I believe the provided code already defines something called makeStack.
