### ISSUE TITLE
forEach

### ISSUE THREAD

**Issue by enartey** [enartey/WebAppsLabs#61]
Given a function f, applies the function to each value stored in the list (not the items, the values). Returns the list.

**Comment by enartey** [comment]
@skiadas, our forEach function is reversing the print out of the list for some reason. We have been looking at it for some time and cannot come up with a reason why. Do you mind shedding some light on what the error could be?

**Comment by skiadas** [comment]
Hm a lot of things seem out of place in the code, in particular how you are creating your "iterator". Seems you're attaching it an extra item property that it is not meant to have. But anyway technically that part should be correct. I'm very skeptical about the line:

```
 secondIterator.item.value = f(secondIterator.next());
```

Why are you changing the value of the item? That's not what `forEach` is supposed to do. In any case it will probably be changing the value of the wrong item, as the call to next happens first and that changes what `secondIterator.item` is. Actually I'm not quite sure which side will get resolved first, but the fact that your code depends on it is worrisome at best, as the object pointed to by `secondIterator.item` changes some time halfway through that code.

All this feels more complicated than it needs to be. I would take a step back and clear some things. But regardless, that assignment is the most fishy part of the code I'd say, and totally not needed. You are just supposed to call `f` with the correct input, not do anything with the returned values.

**Comment by enartey** [comment]
@skiadas  hmm, I'll take another look at it. The issue started with the document's Read Me. is iterator supposed to return the values or the item? thats what started us on the path of confusion for the past few days. Because the readme says it should iterate over values meaning it should access the value of each item thus it should return the value of each item and not just the item. 

Thats why we have ended up going along that spiral. I think I'll leave everything for now and take a fresh look at it tomorrow.

**Comment by skiadas** [comment]
Yes the iterator should be returning the values. Your iterator works I think, it's just not the best way of writing it. To begin with, you are assuming that you can change the object returned to you by `Iterator.new`, and that you can add properties to it. But anyway that's not the source of your problems.

The problem is I believe in forEach, which is changing the values stored in the items. And it shouldn't do that. And it's even unclear which item it's changing. What is the test you're running btw?

**Comment by enartey** [comment]
``` Javascript
it("forEach #86", function(){
        //these functions are applied to the value,
        //not to the item
        var f = function(value){
            console.log("VALUE BEFORE: ", value);
            return value*3;
        }
        var h = function(value){
            console.log("VALUE AFTER: ", value);
        }
        DL2.forEach(f);
        DL2.forEach(h);
        expect(DL2.sentinel.next.value).to.equal(3);
    });
```

**Comment by enartey** [comment]
@skiadas I thought by applying the function to each value stored in the list, the foreach should be able to "alter" the value...

**Comment by enartey** [comment]
@skiadas I think I understand it now. the function should just run on the values and return the list as it was before. nothing should change in the list. the function being given to forEach should just have access to the values right?

**Comment by skiadas** [comment]
Right.

**Comment by enartey** [comment]
thanks @skiadas will change the implementation tomorrow. I feel like my brain is fried right now
