### ISSUE TITLE
Test: first

### ISSUE THREAD

**Issue by dakotaraymccoy** [enartey/WebAppsLabs#74]
test code for DL first()

**Comment by dakotaraymccoy** [comment]
Returns the first item (not the value), if there is one. Throws an exception if the list is empty.

**Comment by enartey** [comment]
@skiadas the test to check for the error thrown when the list is empty is failing for some reason I do not understand. We are throwing a new error, when the list is empty as seen below 

``` Javascript
first: function(){
      if (this.isEmpty()){
         throw new Error("List is Empty");
      }
      return this.sentinel.next;
   }
```

and the test is:

``` Javascript
describe("proto methods", function(){
    beforeEach(function(){
        DL1 = DLList.new();
        DL2 = DLList.new();
        DL2.push(arg1); //arg 1 is set to 1
        DL2.push(arg2); //arg 2 is set to 2
        DL2.push(3);
    });


it("first #74", function(){
        expect(DL2.first().value).to.equal(1);
        expect(DL1.first()).to.throw(Error);
    });

```

Below is an image of the error message we receive. 

![screen shot 2015-03-16 at 3 45 03 pm](https://cloud.githubusercontent.com/assets/10490549/6674922/7fc07b30-cbf3-11e4-921c-158057ab6927.png)

**Comment by enartey** [comment]
@skiadas, just solved the error. You can ignore my question. Thanks.
